name: Kickoff Poller

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 18,20,22,0 * * *"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://f1diots-backend.herokuapp.com/'
        method: 'GET'
        timeout: 90000
        preventFailureOnNoResponse: true
